import "./globals.css";

export const metadata = {
  title: "AL ALA",
  description: "Generated by T-Rex",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="w-full antialiased"
      >
        {children}
      </body>
    </html>
  );
}
