import ".";

export const metadata = {
  title: "AL ALAM",
  description: "Generated by T-Rex",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="w-full antialiased"
      >
        {children}
      </body>
    </html>
  );
}
